on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  linux:
    name: Macity mac
    runs-on: macos-latest

    steps:
    - name: Install
      run: brew install ninja

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run: |
        git submodule init
        git submodule update --remote --merge

    - name: Build
      run: make debug duckdb_debug

    - name: Test
      run: ./duckdb/build/debug/test/unittest --test-dir . "[scrooge]"
